### ISSUE TITLE
Font size on Linux Lubuntu 23.04

### ISSUE THREAD

**Issue by jozsefk9** [ThorstenRhau/WezTerm#1]
Hi!
`font_size = 11.0` in configuration file does nothing at all for me on Linux (Lubuntu 23.04). Not only 11.0 but whatever I use font remains the same.

**Comment by ThorstenRhau** [comment]
Hello jozefk9
My configuration is for macOS. You may want to change or remove the configuration on line 15 where I configure a "front_end" that is specific for macOS.

Furthermore you may want to check that you have the fonts that are configured on lines 36, 41, and 55 installed on your system.

If you have everything taken care of that I mention above and still have the question about font_size = 11.0 on line 56, that size is only for the font on the tab bar.

I hope that this helps you.
With kind regards
Thorsten
